In [34]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import math
from prettytable import PrettyTable

In [2]:
df = pd.read_csv('Bid_ask_g10.csv')
df.Dates = pd.to_datetime(df['Dates'], infer_datetime_format=True)

In [3]:
df.dtypes

Dates         datetime64[ns]
PX_BID_AUD           float64
PX_ASK_AUD           float64
PX_BID_CAD           float64
PX_ASK_CAD           float64
PX_BID_CHF           float64
PX_ASK_CHF           float64
PX_BID_EUR           float64
PX_ASK_EUR           float64
PX_BID_JPY           float64
PX_ASK_JPY           float64
PX_BID_NOK           float64
PX_ASK_NOK           float64
PX_BID_NZD           float64
PX_ASK_NZD           float64
PX_BID_SEK           float64
PX_ASK_SEK           float64
PX_BID_GBP           float64
PX_ASK_GBP           float64
dtype: object

In [4]:
df

,Dates,PX_BID_AUD,PX_ASK_AUD,PX_BID_CAD,PX_ASK_CAD,PX_BID_CHF,PX_ASK_CHF,PX_BID_EUR,PX_ASK_EUR,PX_BID_JPY,PX_ASK_JPY,PX_BID_NOK,PX_ASK_NOK,PX_BID_NZD,PX_ASK_NZD,PX_BID_SEK,PX_ASK_SEK,PX_BID_GBP,PX_ASK_GBP
0,2000-01-03,0.6582,0.6587,1.4463,1.4473,1.5667,1.5672,1.0241,1.0245,101.53,101.45,7.8859,7.8909,0.5245,0.5255,8.3742,8.3792,1.6359,1.6364
1,2000-01-04,0.6547,0.6552,1.4525,1.4530,1.5568,1.5578,1.0294,1.0298,103.20,103.23,7.9444,7.9494,0.5190,0.5197,8.3785,8.3835,1.6357,1.6362
2,2000-01-05,0.6576,0.6581,1.4495,1.4505,1.5553,1.5491,1.0319,1.0323,104.12,104.15,7.9405,7.9455,0.5198,0.5205,8.3646,8.3696,1.6421,1.6431
3,2000-01-06,0.6530,0.6535,1.4594,1.4604,1.5528,1.5537,1.0325,1.0329,105.21,105.24,7.9395,7.9445,0.5142,0.5149,8.3694,8.3744,1.6471,1.6476
4,2000-01-07,0.6546,0.6551,1.4553,1.4563,1.5641,1.5651,1.0293,1.0298,105.32,105.36,7.9723,7.9773,0.5170,0.5180,8.4142,8.4192,1.6388,1.6398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5342,2020-06-24,0.6868,0.6871,1.3637,1.3639,0.9478,0.9481,1.1250,1.1252,107.03,107.05,9.6396,9.6898,0.6408,0.6411,9.3543,9.3749,1.2417,1.2421
5343,2020-06-25,0.6886,0.6888,1.3636,1.3640,0.9484,0.9486,1.1217,1.1218,107.18,107.20,9.6520,9.6702,0.6428,0.6431,9.3034,9.3240,1.2417,1.2421
5344,2020-06-26,0.6862,0.6868,1.3683,1.3693,0.9471,0.9484,1.1215,1.1222,107.19,107.25,9.6400,9.7557,0.6416,0.6430,9.3215,9.3517,1.2326,1.2346
5345,2020-06-29,0.6860,0.6871,1.3657,1.3660,0.9511,0.9513,1.1241,1.1243,107.56,107.59,9.6698,9.6790,0.6419,0.6424,9.3263,9.3330,1.2296,1.2301
5346,2020-06-30,0.6902,0.6905,1.3573,1.3579,0.9472,0.9474,1.1233,1.1235,107.92,107.94,9.6173,9.6330,0.6452,0.6457,9.3154,9.3268,1.2399,1.2403

In [5]:
bid_cols = list(set(df.columns[df.columns.str.contains('BID')].values))
ask_cols = list(set(df.columns[df.columns.str.contains('ASK')].values))
bid_cols.sort()
ask_cols.sort()

In [6]:
print(bid_cols)
print(ask_cols)

['PX_BID_AUD', 'PX_BID_CAD', 'PX_BID_CHF', 'PX_BID_EUR', 'PX_BID_GBP', 'PX_BID_JPY', 'PX_BID_NOK', 'PX_BID_NZD', 'PX_BID_SEK']
['PX_ASK_AUD', 'PX_ASK_CAD', 'PX_ASK_CHF', 'PX_ASK_EUR', 'PX_ASK_GBP', 'PX_ASK_JPY', 'PX_ASK_NOK', 'PX_ASK_NZD', 'PX_ASK_SEK']

In [7]:
for i,v in zip(bid_cols,ask_cols):
    df['spot'+i[7:]] = (df[i]+df[v])/2

In [8]:
spot_cols = list(set(df.columns[df.columns.str.contains('spot')].values))
spot_cols.sort()

In [9]:
for i in spot_cols:
    df['return_'+i[4:]] = (df[i]/df[i].shift(1) - 1)*100

In [10]:
return_cols = list(set(df.columns[df.columns.str.contains('return')].values))
return_cols.sort()
returns = df[return_cols]

In [11]:
#(ask price – bid price) / (ask price + Bid Price)

for i,v in zip(ask_cols, bid_cols):
    df['liquidity_'+i[7:]] = (df[i] - df[v])/(df[i] + df[v])

In [13]:
liquid_cols = list(set(df.columns[df.columns.str.contains('liquidity')].values))
liquid_cols.sort()
liquidities = df[liquid_cols]

In [14]:
#csfs:cross_sectional_factor_score
for i in liquid_cols:
    df['csfs_'+i[10:]] = 1/(1+np.exp(-(df[i] - df[liquid_cols].mean(axis=1))/df[liquid_cols].std(axis=1)))

In [15]:
csfs_cols = list(set(df.columns[df.columns.str.contains('csfs')].values))
csfs_cols.sort()
csfs = df[csfs_cols]

In [16]:
#benchmark return:equally Weighted
df['bench_return'] = df[return_cols].mean(axis=1)

In [17]:
#portfolio weight of currency i = csfs of i*1/9 / summation of csfs*1/9
for i in csfs_cols:
    df['pw_'+i[5:]] = df[i]/df[csfs_cols].sum(axis=1)

In [18]:
csfs

,csfs_AUD,csfs_CAD,csfs_CHF,csfs_EUR,csfs_GBP,csfs_JPY,csfs_NOK,csfs_NZD,csfs_SEK
0,0.580382,0.556231,0.422752,0.448101,0.418003,0.128902,0.535707,0.878523,0.522413
1,0.627953,0.322899,0.539371,0.352779,0.298034,0.288675,0.529650,0.907656,0.505122
2,0.595946,0.585177,0.067895,0.538158,0.572706,0.522483,0.575907,0.681176,0.570969
3,0.609135,0.548798,0.467676,0.327062,0.272928,0.261812,0.506258,0.906992,0.481358
4,0.509298,0.467547,0.441711,0.361438,0.426103,0.309971,0.435176,0.930054,0.417611
...,...,...,...,...,...,...,...,...,...
5342,0.409803,0.368803,0.392618,0.373122,0.393415,0.374387,0.921701,0.414320,0.664667
5343,0.385601,0.386463,0.362239,0.327747,0.395063,0.355232,0.822553,0.439120,0.874932
5344,0.384895,0.375549,0.417945,0.368663,0.434823,0.364530,0.930107,0.473076,0.545843
5345,0.894074,0.311930,0.307687,0.293305,0.402324,0.339430,0.680407,0.596563,0.565428
5346,0.420077,0.423587,0.319240,0.305409,0.368089,0.308421,0.881437,0.584037,0.770638

In [19]:
pw_cols = list(set(df.columns[df.columns.str.contains('pw')].values))
pw_cols.sort()
portfolio_weights = df[pw_cols]

In [20]:
portfolio_weights

,pw_AUD,pw_CAD,pw_CHF,pw_EUR,pw_GBP,pw_JPY,pw_NOK,pw_NZD,pw_SEK
0,0.129232,0.123854,0.094133,0.099777,0.093075,0.028702,0.119284,0.195618,0.116324
1,0.143626,0.073854,0.123366,0.080688,0.068167,0.066026,0.121142,0.207600,0.115532
2,0.126517,0.124230,0.014414,0.114248,0.121583,0.110921,0.122262,0.144611,0.121214
3,0.139008,0.125239,0.106726,0.074637,0.062284,0.059747,0.115531,0.206980,0.109849
4,0.118472,0.108759,0.102750,0.084077,0.099119,0.072105,0.101229,0.216347,0.097143
...,...,...,...,...,...,...,...,...,...
5342,0.095019,0.085513,0.091035,0.086514,0.091220,0.086808,0.213711,0.096067,0.154114
5343,0.088665,0.088863,0.083294,0.075362,0.090841,0.081682,0.189138,0.100972,0.201182
5344,0.089606,0.087430,0.097300,0.085827,0.101229,0.084865,0.216534,0.110135,0.127075
5345,0.203608,0.071036,0.070070,0.066794,0.091622,0.077299,0.154950,0.135856,0.128765
5346,0.095888,0.096689,0.072870,0.069713,0.084021,0.070401,0.201198,0.133313,0.175907

In [21]:
returns.columns

Index(['return_AUD', 'return_CAD', 'return_CHF', 'return_EUR', 'return_GBP',
       'return_JPY', 'return_NOK', 'return_NZD', 'return_SEK'],
      dtype='object')

In [22]:
returns.columns = ['AUD', 'CAD', 'CHF', 'EUR', 'GBP', 'JPY', 'NOK', 'NZD', 'SEK']
portfolio_weights.columns = ['AUD', 'CAD', 'CHF', 'EUR', 'GBP', 'JPY', 'NOK', 'NZD', 'SEK']

In [24]:
#Simple Portfolio returns using csfs weights
df['simple_portfolio_return'] = returns.mul(portfolio_weights).sum(axis = 1)

In [26]:
#lets see both benchmark and simple portfolio return
df[['bench_return', 'simple_portfolio_return' ]]

      bench_return  simple_portfolio_return
0              NaN                 0.000000
1         0.131719                -0.096455
2         0.156195                 0.199986
3         0.045928                -0.137576
4         0.170205                 0.225180
...            ...                      ...
5342      0.046529                 0.268619
5343     -0.012622                -0.068461
5344     -0.015350                 0.033700
5345      0.005863                -0.026812
5346      0.060547                 0.003055

[5347 rows x 2 columns]

In [28]:
Number_of_days = df.shape[0]
Annualized_bench_return = (((1 + df['bench_return']/100).prod())**(365/Number_of_days) -1)*100
Annualized_portfolio_return = (((1 + df['simple_portfolio_return']/100).prod())**(365/Number_of_days) -1)*100

In [29]:
print(Annualized_bench_return)
print(Annualized_portfolio_return)

0.7136926936563759
1.02621475977549

In [31]:
Annualized_benchmark_risk = df['bench_return'].std()*math.sqrt(252)
Annualized_portfolio_risk = df['simple_portfolio_return'].std()*math.sqrt(252)

In [33]:
print(Annualized_benchmark_risk)
print(Annualized_portfolio_risk)

2.743099179179861
3.601913254115163

In [41]:
cum_returns_simple_portfolio = ((1 + df['simple_portfolio_return']/100).cumprod())*100
drawdown_simple_portfolio =  (1 - cum_returns_simple_portfolio.div(cum_returns_simple_portfolio.cummax()))*100
simple_port_max_draw = drawdown_simple_portfolio.max()

In [42]:
cum_returns_bench_portfolio = ((1 + df['bench_return']/100).cumprod())*100
drawdown_bench_portfolio =  (1 - cum_returns_bench_portfolio.div(cum_returns_bench_portfolio.cummax()))*100
bench_port_max_draw = drawdown_bench_portfolio.max()

In [47]:
table = PrettyTable()
table.align = "l"
table.hrules = 1

table.title = 'Summary Table of Above Calculations'
table.field_names = ['Parameter', 'Value']

table.add_row(['Annualized Benchmark Return %', Annualized_bench_return])
table.add_row(['Annualized Benchmark Risk %', Annualized_benchmark_risk])
table.add_row(['Sharpe Ratio:Benchmark', Annualized_bench_return/Annualized_benchmark_risk])
table.add_row(['Maximum Drawdown:BenchMark Portfolio %', bench_port_max_draw ])
table.add_row(['Annualized Return/Maximum Drawdown:Benchmark Portfolio %', Annualized_bench_return/bench_port_max_draw ])



table.add_row(['Annualized Simple Portfolio Return %', Annualized_portfolio_return])
table.add_row(['Annualized Simple Portfolio Risk %', Annualized_portfolio_risk])
table.add_row(['Sharpe Ratio:Simple Portfolio', Annualized_portfolio_return/Annualized_portfolio_risk])
table.add_row(['Maximum Drawdown:Simple Portfolio %', simple_port_max_draw ])
table.add_row(['Annualized Return/Maximum Drawdown:Simple Portfolio %', Annualized_portfolio_return/simple_port_max_draw ])

print(table)

+--------------------------------------------------------------------------------+
|                      Summary Table of Above Calculations                       |
+----------------------------------------------------------+---------------------+
|                        Parameter                         |        Value        |
+----------------------------------------------------------+---------------------+
|              Annualized Benchmark Return %               |  0.7136926936563759 |
+----------------------------------------------------------+---------------------+
|               Annualized Benchmark Risk %                |  2.743099179179861  |
+----------------------------------------------------------+---------------------+
|                  Sharpe Ratio:Benchmark                  | 0.26017750253921096 |
+----------------------------------------------------------+---------------------+
|          Maximum Drawdown:BenchMark Portfolio %          |   8.9683648591956   |
+----------------------------------------------------------+---------------------+
| Annualized Return/Maximum Drawdown:Benchmark Portfolio % |  0.0795789092952212 |
+----------------------------------------------------------+---------------------+
|           Annualized Simple Portfolio Return %           |   1.02621475977549  |
+----------------------------------------------------------+---------------------+
|            Annualized Simple Portfolio Risk %            |  3.601913254115163  |
+----------------------------------------------------------+---------------------+
|              Sharpe Ratio:Simple Portfolio               | 0.28490823831002765 |
+----------------------------------------------------------+---------------------+
|           Maximum Drawdown:Simple Portfolio %            |  10.743695170214462 |
+----------------------------------------------------------+---------------------+
|  Annualized Return/Maximum Drawdown:Simple Portfolio %   | 0.09551785894117146 |
+----------------------------------------------------------+---------------------+

In [ ]:
#We can see that Simple Portfolio constructed using cross sectional factor score weights offers 
#much better Sharpe and Return per unit drawdown,